### ISSUE TITLE
FR: global search

### ISSUE THREAD

**Issue by quesada** [XRoemer/Organon#33]
Congrats, organon beats similar tools for me (like scrivener).
If I can, here's a Feature Request: global search. 
I'd like to search the sub documents. I use the file explorer for that now, not ideal.
Thanks for your efforts!

**Comment by XRoemer** [comment]
Thanks.

There's already one search function inside the "new tab" menu but its button is disabled, because it is not implemented yet. The plan is to search on freely choosable files and open the files in which the search terms are found in new tabs. But that will open the whole file in which the search term is found, which might be to

I'm still thinking about how search results should be represented and what has to be possible after search. Any suggestions are welcome.
Xaver

**Comment by XRoemer** [comment]
I'm not shure, if an Organon search function would make much sense. 
One can use the usual search function of Office. All opened (visible) files will be searched.

As long as noone else has proposals for the need of a search function in Organon, I'm closing this FR.
