### ISSUE TITLE
Crashes when creating a new project

### ISSUE THREAD

**Issue by markrs** [XRoemer/Organon#43]
I have installed Organon for the first time with LibreOffice 5.0.0.5 64bit, I am using a upto date version of windows 10 64bit on a Dell Venue Pro 11.

As soon as I select "New Project" it immediately crashes. I can select "Open Project" but don't have any project to try out and see if that woud get any further. Click "Load Manual" also crashes Libre Office. Let me know if there is any other information you need.

**Comment by XRoemer** [comment]
Thanks for your remark. I'll have a look as soon as possible.

**Comment by XRoemer** [comment]
I can confirm the errors.
LO5 64bit crashes immediately after clicking any of the buttons in Organon's startmenu.
LO5 32bit works but has some issues, too. It crashes when closing LO or using Organon designs.

Some changes of path settings in LO5 I noticed are: 
64bit version installs to C:\Program Files instead of C:\Program Files (x86) as before.

Organon is installed to: 
C:\Users\Homer\AppData\Roaming\LibreOffice\4\user\uno_packages\cache\uno_packages
(before: C:\Program Files (x86)\LibreOffice 4\share\uno_packages\cache\uno_packages)

Obviously it should be: ...\LibreOffice\5\user...

Working out whether these problems are depending on LO or Organon will need some time. So if you want to give Organon a try, I can only advise you for the moment, to install LO4x.

**Comment by XRoemer** [comment]
At the moment it looks to me like there is a serious problem with LO5 64bit and users should have problems with other extensions as well. I'm waiting for reactions on LO's mailing lists.

**Comment by XRoemer** [comment]
As I've seen some serious bugs and that the API of the sidebar will be changed, I wait for LO 5.1 before I do any effort of getting Organon to work with LO 5.x

I put a generally warning not to use Organon with LO5 and close this bug.

**Comment by markrs** [comment]
Thanks for looking into the issue

**Comment by IaoP** [comment]
The same with me in 5.3 developpers edition, 64 bit.

**Comment by XRoemer** [comment]
What's your platform?
Send me a logfile, so I might see, where the crash happens. See #89
